### ISSUE TITLE
Business calendar: optimistic lock exception should be thrown while simultaneous editing business calendar

### ISSUE THREAD

**Issue by artemy63** [jmix-projects/jmix-old#617]
TC: 
1. Create business calendar with some working days, save it.
2. Open created business calendar for editing.
3. Open again previously created business calendar for editing in different tab.
3. Change something in first editor and save business calendar.
4. Change something in second editor and try to save business calendar.

ER: Optimistic lock exception
AR: IllegalStateException: No results
```
at io.jmix.core.FluentLoader$ById.one(FluentLoader.java:216)
	at io.jmix.businesscalendarui.screen.calendar.BusinessCalendarEdit.saveBusinessDayEntities(BusinessCalendarEdit.java:382)
	at io.jmix.businesscalendarui.screen.calendar.BusinessCalendarEdit.saveBusinessCalendarEntitiesToDatabase(BusinessCalendarEdit.java:318)
	at io.jmix.businesscalendarui.screen.calendar.BusinessCalendarEdit.onPreCommit(BusinessCalendarEdit.java:134)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
```

**Comment by artemy63** [comment]
Issue moved to [Haulmont/jmix-misc #11](https://github.com/Haulmont/jmix-misc/issues/11) via [**ZenHub**](https://www.zenhub.com/)
